# supabase/config.toml

project_id = "serzklumwbcvzbtezxrd"

[api]
enabled = true
port = 60001
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 60002
shadow_port = 60000
major_version = 17

[db.pooler]
enabled = false
port = 60009
pool_mode = "transaction"

[realtime]
enabled = true

[studio]
enabled = true
port = 60003
api_url = "http://127.0.0.1:60001"

[inbucket]
enabled = true
port = 60005
smtp_port = 60006
pop3_port = 60007

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.create-test-users]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

